module GL_EXT_texture_compression_latc
  COMPRESSED_LUMINANCE_ALPHA_LATC2_EXT        = 0x8C72
  COMPRESSED_LUMINANCE_LATC1_EXT              = 0x8C70
  COMPRESSED_SIGNED_LUMINANCE_ALPHA_LATC2_EXT = 0x8C73
  COMPRESSED_SIGNED_LUMINANCE_LATC1_EXT       = 0x8C71
end