module GL_EXT_direct_state_access
  PROGRAM_MATRIX_EXT             = 0x8E2D
  PROGRAM_MATRIX_STACK_DEPTH_EXT = 0x8E2F
  TRANSPOSE_PROGRAM_MATRIX_EXT   = 0x8E2E

  FUNCTIONS = {
    glBindMultiTextureEXT: [ :void, :uint, :uint, :uint ].freeze,
    glCheckNamedFramebufferStatusEXT: [ :uint, :uint, :uint ].freeze,
    glClientAttribDefaultEXT: [ :void, :uint ].freeze,
    glCompressedMultiTexImage1DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :pointer ].freeze,
    glCompressedMultiTexImage2DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :int, :pointer ].freeze,
    glCompressedMultiTexImage3DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :int, :int, :pointer ].freeze,
    glCompressedMultiTexSubImage1DEXT: [ :void, :uint, :uint, :int, :int, :int, :uint, :int, :pointer ].freeze,
    glCompressedMultiTexSubImage2DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :uint, :int, :pointer ].freeze,
    glCompressedMultiTexSubImage3DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :int, :uint, :int, :pointer ].freeze,
    glCompressedTextureImage1DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :pointer ].freeze,
    glCompressedTextureImage2DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :int, :pointer ].freeze,
    glCompressedTextureImage3DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :int, :int, :pointer ].freeze,
    glCompressedTextureSubImage1DEXT: [ :void, :uint, :uint, :int, :int, :int, :uint, :int, :pointer ].freeze,
    glCompressedTextureSubImage2DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :uint, :int, :pointer ].freeze,
    glCompressedTextureSubImage3DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :int, :uint, :int, :pointer ].freeze,
    glCopyMultiTexImage1DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :int ].freeze,
    glCopyMultiTexImage2DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :int, :int ].freeze,
    glCopyMultiTexSubImage1DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int ].freeze,
    glCopyMultiTexSubImage2DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :int ].freeze,
    glCopyMultiTexSubImage3DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :int, :int ].freeze,
    glCopyTextureImage1DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :int ].freeze,
    glCopyTextureImage2DEXT: [ :void, :uint, :uint, :int, :uint, :int, :int, :int, :int, :int ].freeze,
    glCopyTextureSubImage1DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int ].freeze,
    glCopyTextureSubImage2DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :int ].freeze,
    glCopyTextureSubImage3DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :int, :int ].freeze,
    glDisableClientStateIndexedEXT: [ :void, :uint, :uint ].freeze,
    glDisableVertexArrayAttribEXT: [ :void, :uint, :uint ].freeze,
    glDisableVertexArrayEXT: [ :void, :uint, :uint ].freeze,
    glEnableClientStateIndexedEXT: [ :void, :uint, :uint ].freeze,
    glEnableVertexArrayAttribEXT: [ :void, :uint, :uint ].freeze,
    glEnableVertexArrayEXT: [ :void, :uint, :uint ].freeze,
    glFlushMappedNamedBufferRangeEXT: [ :void, :uint, :int64, :int64 ].freeze,
    glFramebufferDrawBufferEXT: [ :void, :uint, :uint ].freeze,
    glFramebufferDrawBuffersEXT: [ :void, :uint, :int, :pointer ].freeze,
    glFramebufferReadBufferEXT: [ :void, :uint, :uint ].freeze,
    glGenerateMultiTexMipmapEXT: [ :void, :uint, :uint ].freeze,
    glGenerateTextureMipmapEXT: [ :void, :uint, :uint ].freeze,
    glGetCompressedMultiTexImageEXT: [ :void, :uint, :uint, :int, :pointer ].freeze,
    glGetCompressedTextureImageEXT: [ :void, :uint, :uint, :int, :pointer ].freeze,
    glGetDoubleIndexedvEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetFloatIndexedvEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetFramebufferParameterivEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetMultiTexEnvfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetMultiTexEnvivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetMultiTexGendvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetMultiTexGenfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetMultiTexGenivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetMultiTexImageEXT: [ :void, :uint, :uint, :int, :uint, :uint, :pointer ].freeze,
    glGetMultiTexLevelParameterfvEXT: [ :void, :uint, :uint, :int, :uint, :pointer ].freeze,
    glGetMultiTexLevelParameterivEXT: [ :void, :uint, :uint, :int, :uint, :pointer ].freeze,
    glGetMultiTexParameterfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetMultiTexParameterIivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetMultiTexParameterIuivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetMultiTexParameterivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetNamedBufferParameterivEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetNamedBufferPointervEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetNamedBufferSubDataEXT: [ :void, :uint, :int64, :int64, :pointer ].freeze,
    glGetNamedFramebufferAttachmentParameterivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetNamedProgramivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetNamedProgramLocalParameterdvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetNamedProgramLocalParameterfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetNamedProgramStringEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetNamedRenderbufferParameterivEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetPointerIndexedvEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetTextureImageEXT: [ :void, :uint, :uint, :int, :uint, :uint, :pointer ].freeze,
    glGetTextureLevelParameterfvEXT: [ :void, :uint, :uint, :int, :uint, :pointer ].freeze,
    glGetTextureLevelParameterivEXT: [ :void, :uint, :uint, :int, :uint, :pointer ].freeze,
    glGetTextureParameterfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetTextureParameterIivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetTextureParameterIuivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetTextureParameterivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetVertexArrayIntegeri_vEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetVertexArrayIntegervEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetVertexArrayPointeri_vEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetVertexArrayPointervEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glMapNamedBufferEXT: [ :pointer, :uint, :uint ].freeze,
    glMapNamedBufferRangeEXT: [ :pointer, :uint, :int64, :int64, :uint ].freeze,
    glMatrixFrustumEXT: [ :void, :uint, :double, :double, :double, :double, :double, :double ].freeze,
    glMatrixLoaddEXT: [ :void, :uint, :pointer ].freeze,
    glMatrixLoadfEXT: [ :void, :uint, :pointer ].freeze,
    glMatrixLoadIdentityEXT: [ :void, :uint ].freeze,
    glMatrixLoadTransposedEXT: [ :void, :uint, :pointer ].freeze,
    glMatrixLoadTransposefEXT: [ :void, :uint, :pointer ].freeze,
    glMatrixMultdEXT: [ :void, :uint, :pointer ].freeze,
    glMatrixMultfEXT: [ :void, :uint, :pointer ].freeze,
    glMatrixMultTransposedEXT: [ :void, :uint, :pointer ].freeze,
    glMatrixMultTransposefEXT: [ :void, :uint, :pointer ].freeze,
    glMatrixOrthoEXT: [ :void, :uint, :double, :double, :double, :double, :double, :double ].freeze,
    glMatrixPopEXT: [ :void, :uint ].freeze,
    glMatrixPushEXT: [ :void, :uint ].freeze,
    glMatrixRotatedEXT: [ :void, :uint, :double, :double, :double, :double ].freeze,
    glMatrixRotatefEXT: [ :void, :uint, :float, :float, :float, :float ].freeze,
    glMatrixScaledEXT: [ :void, :uint, :double, :double, :double ].freeze,
    glMatrixScalefEXT: [ :void, :uint, :float, :float, :float ].freeze,
    glMatrixTranslatedEXT: [ :void, :uint, :double, :double, :double ].freeze,
    glMatrixTranslatefEXT: [ :void, :uint, :float, :float, :float ].freeze,
    glMultiTexBufferEXT: [ :void, :uint, :uint, :uint, :uint ].freeze,
    glMultiTexCoordPointerEXT: [ :void, :uint, :int, :uint, :int, :pointer ].freeze,
    glMultiTexEnvfEXT: [ :void, :uint, :uint, :uint, :float ].freeze,
    glMultiTexEnvfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexEnviEXT: [ :void, :uint, :uint, :uint, :int ].freeze,
    glMultiTexEnvivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexGendEXT: [ :void, :uint, :uint, :uint, :double ].freeze,
    glMultiTexGendvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexGenfEXT: [ :void, :uint, :uint, :uint, :float ].freeze,
    glMultiTexGenfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexGeniEXT: [ :void, :uint, :uint, :uint, :int ].freeze,
    glMultiTexGenivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexImage1DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glMultiTexImage2DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glMultiTexImage3DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glMultiTexParameterfEXT: [ :void, :uint, :uint, :uint, :float ].freeze,
    glMultiTexParameterfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexParameteriEXT: [ :void, :uint, :uint, :uint, :int ].freeze,
    glMultiTexParameterIivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexParameterIuivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexParameterivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glMultiTexRenderbufferEXT: [ :void, :uint, :uint, :uint ].freeze,
    glMultiTexSubImage1DEXT: [ :void, :uint, :uint, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glMultiTexSubImage2DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glMultiTexSubImage3DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glNamedBufferDataEXT: [ :void, :uint, :int64, :pointer, :uint ].freeze,
    glNamedBufferSubDataEXT: [ :void, :uint, :int64, :int64, :pointer ].freeze,
    glNamedCopyBufferSubDataEXT: [ :void, :uint, :uint, :int64, :int64, :int64 ].freeze,
    glNamedFramebufferRenderbufferEXT: [ :void, :uint, :uint, :uint, :uint ].freeze,
    glNamedFramebufferTexture1DEXT: [ :void, :uint, :uint, :uint, :uint, :int ].freeze,
    glNamedFramebufferTexture2DEXT: [ :void, :uint, :uint, :uint, :uint, :int ].freeze,
    glNamedFramebufferTexture3DEXT: [ :void, :uint, :uint, :uint, :uint, :int, :int ].freeze,
    glNamedFramebufferTextureEXT: [ :void, :uint, :uint, :uint, :int ].freeze,
    glNamedFramebufferTextureFaceEXT: [ :void, :uint, :uint, :uint, :int, :uint ].freeze,
    glNamedFramebufferTextureLayerEXT: [ :void, :uint, :uint, :uint, :int, :int ].freeze,
    glNamedProgramLocalParameter4dEXT: [ :void, :uint, :uint, :uint, :double, :double, :double, :double ].freeze,
    glNamedProgramLocalParameter4dvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glNamedProgramLocalParameter4fEXT: [ :void, :uint, :uint, :uint, :float, :float, :float, :float ].freeze,
    glNamedProgramLocalParameter4fvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glNamedProgramLocalParameters4fvEXT: [ :void, :uint, :uint, :uint, :int, :pointer ].freeze,
    glNamedProgramStringEXT: [ :void, :uint, :uint, :uint, :int, :pointer ].freeze,
    glNamedRenderbufferStorageEXT: [ :void, :uint, :uint, :int, :int ].freeze,
    glNamedRenderbufferStorageMultisampleEXT: [ :void, :uint, :int, :uint, :int, :int ].freeze,
    glProgramUniform1dEXT: [ :void, :uint, :int, :double ].freeze,
    glProgramUniform1dvEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform1fEXT: [ :void, :uint, :int, :float ].freeze,
    glProgramUniform1fvEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform1iEXT: [ :void, :uint, :int, :int ].freeze,
    glProgramUniform1ivEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform1uiEXT: [ :void, :uint, :int, :uint ].freeze,
    glProgramUniform1uivEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform2dEXT: [ :void, :uint, :int, :double, :double ].freeze,
    glProgramUniform2dvEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform2fEXT: [ :void, :uint, :int, :float, :float ].freeze,
    glProgramUniform2fvEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform2iEXT: [ :void, :uint, :int, :int, :int ].freeze,
    glProgramUniform2ivEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform2uiEXT: [ :void, :uint, :int, :uint, :uint ].freeze,
    glProgramUniform2uivEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform3dEXT: [ :void, :uint, :int, :double, :double, :double ].freeze,
    glProgramUniform3dvEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform3fEXT: [ :void, :uint, :int, :float, :float, :float ].freeze,
    glProgramUniform3fvEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform3iEXT: [ :void, :uint, :int, :int, :int, :int ].freeze,
    glProgramUniform3ivEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform3uiEXT: [ :void, :uint, :int, :uint, :uint, :uint ].freeze,
    glProgramUniform3uivEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform4dEXT: [ :void, :uint, :int, :double, :double, :double, :double ].freeze,
    glProgramUniform4dvEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform4fEXT: [ :void, :uint, :int, :float, :float, :float, :float ].freeze,
    glProgramUniform4fvEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform4iEXT: [ :void, :uint, :int, :int, :int, :int, :int ].freeze,
    glProgramUniform4ivEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniform4uiEXT: [ :void, :uint, :int, :uint, :uint, :uint, :uint ].freeze,
    glProgramUniform4uivEXT: [ :void, :uint, :int, :int, :pointer ].freeze,
    glProgramUniformMatrix2dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix2fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix2x3dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix2x3fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix2x4dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix2x4fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix3dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix3fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix3x2dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix3x2fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix3x4dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix3x4fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix4dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix4fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix4x2dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix4x2fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix4x3dvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glProgramUniformMatrix4x3fvEXT: [ :void, :uint, :int, :int, :uchar, :pointer ].freeze,
    glPushClientAttribDefaultEXT: [ :void, :uint ].freeze,
    glTextureBufferEXT: [ :void, :uint, :uint, :uint, :uint ].freeze,
    glTextureImage1DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glTextureImage2DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glTextureImage3DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glTextureParameterfEXT: [ :void, :uint, :uint, :uint, :float ].freeze,
    glTextureParameterfvEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glTextureParameteriEXT: [ :void, :uint, :uint, :uint, :int ].freeze,
    glTextureParameterIivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glTextureParameterIuivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glTextureParameterivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glTextureRenderbufferEXT: [ :void, :uint, :uint, :uint ].freeze,
    glTextureSubImage1DEXT: [ :void, :uint, :uint, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glTextureSubImage2DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glTextureSubImage3DEXT: [ :void, :uint, :uint, :int, :int, :int, :int, :int, :int, :int, :uint, :uint, :pointer ].freeze,
    glUnmapNamedBufferEXT: [ :uchar, :uint ].freeze,
    glVertexArrayColorOffsetEXT: [ :void, :uint, :uint, :int, :uint, :int, :int64 ].freeze,
    glVertexArrayEdgeFlagOffsetEXT: [ :void, :uint, :uint, :int, :int64 ].freeze,
    glVertexArrayFogCoordOffsetEXT: [ :void, :uint, :uint, :uint, :int, :int64 ].freeze,
    glVertexArrayIndexOffsetEXT: [ :void, :uint, :uint, :uint, :int, :int64 ].freeze,
    glVertexArrayMultiTexCoordOffsetEXT: [ :void, :uint, :uint, :uint, :int, :uint, :int, :int64 ].freeze,
    glVertexArrayNormalOffsetEXT: [ :void, :uint, :uint, :uint, :int, :int64 ].freeze,
    glVertexArraySecondaryColorOffsetEXT: [ :void, :uint, :uint, :int, :uint, :int, :int64 ].freeze,
    glVertexArrayTexCoordOffsetEXT: [ :void, :uint, :uint, :int, :uint, :int, :int64 ].freeze,
    glVertexArrayVertexAttribIOffsetEXT: [ :void, :uint, :uint, :uint, :int, :uint, :int, :int64 ].freeze,
    glVertexArrayVertexAttribOffsetEXT: [ :void, :uint, :uint, :uint, :int, :uint, :uchar, :int, :int64 ].freeze,
    glVertexArrayVertexOffsetEXT: [ :void, :uint, :uint, :int, :uint, :int, :int64 ].freeze
  }.freeze

  FUNCTIONS_COMPATABILITY = {
    glDisableClientStateiEXT: [ :void, :uint, :uint ].freeze,
    glEnableClientStateiEXT: [ :void, :uint, :uint ].freeze,
    glGetDoublei_vEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetFloati_vEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glGetNamedProgramLocalParameterIivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetNamedProgramLocalParameterIuivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glGetPointeri_vEXT: [ :void, :uint, :uint, :pointer ].freeze,
    glNamedProgramLocalParameterI4iEXT: [ :void, :uint, :uint, :uint, :int, :int, :int, :int ].freeze,
    glNamedProgramLocalParameterI4ivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glNamedProgramLocalParameterI4uiEXT: [ :void, :uint, :uint, :uint, :uint, :uint, :uint, :uint ].freeze,
    glNamedProgramLocalParameterI4uivEXT: [ :void, :uint, :uint, :uint, :pointer ].freeze,
    glNamedProgramLocalParametersI4ivEXT: [ :void, :uint, :uint, :uint, :int, :pointer ].freeze,
    glNamedProgramLocalParametersI4uivEXT: [ :void, :uint, :uint, :uint, :int, :pointer ].freeze,
    glNamedRenderbufferStorageMultisampleCoverageEXT: [ :void, :uint, :int, :int, :uint, :int, :int ].freeze
  }.freeze
end

