module GL_SUN_vertex
  FUNCTIONS = {
    glColor3fVertex3fSUN: [ :void, :float, :float, :float, :float, :float, :float ].freeze,
    glColor3fVertex3fvSUN: [ :void, :pointer, :pointer ].freeze,
    glColor4fNormal3fVertex3fSUN: [ :void, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glColor4fNormal3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer ].freeze,
    glColor4ubVertex2fSUN: [ :void, :uchar, :uchar, :uchar, :uchar, :float, :float ].freeze,
    glColor4ubVertex2fvSUN: [ :void, :pointer, :pointer ].freeze,
    glColor4ubVertex3fSUN: [ :void, :uchar, :uchar, :uchar, :uchar, :float, :float, :float ].freeze,
    glColor4ubVertex3fvSUN: [ :void, :pointer, :pointer ].freeze,
    glNormal3fVertex3fSUN: [ :void, :float, :float, :float, :float, :float, :float ].freeze,
    glNormal3fVertex3fvSUN: [ :void, :pointer, :pointer ].freeze,
    glReplacementCodeuiColor3fVertex3fSUN: [ :void, :uint, :float, :float, :float, :float, :float, :float ].freeze,
    glReplacementCodeuiColor3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer ].freeze,
    glReplacementCodeuiColor4fNormal3fVertex3fSUN: [ :void, :uint, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glReplacementCodeuiColor4fNormal3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer, :pointer ].freeze,
    glReplacementCodeuiColor4ubVertex3fSUN: [ :void, :uint, :uchar, :uchar, :uchar, :uchar, :float, :float, :float ].freeze,
    glReplacementCodeuiColor4ubVertex3fvSUN: [ :void, :pointer, :pointer, :pointer ].freeze,
    glReplacementCodeuiNormal3fVertex3fSUN: [ :void, :uint, :float, :float, :float, :float, :float, :float ].freeze,
    glReplacementCodeuiNormal3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer ].freeze,
    glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN: [ :void, :uint, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer, :pointer, :pointer ].freeze,
    glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN: [ :void, :uint, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer, :pointer ].freeze,
    glReplacementCodeuiTexCoord2fVertex3fSUN: [ :void, :uint, :float, :float, :float, :float, :float ].freeze,
    glReplacementCodeuiTexCoord2fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer ].freeze,
    glReplacementCodeuiVertex3fSUN: [ :void, :uint, :float, :float, :float ].freeze,
    glReplacementCodeuiVertex3fvSUN: [ :void, :pointer, :pointer ].freeze,
    glTexCoord2fColor3fVertex3fSUN: [ :void, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glTexCoord2fColor3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer ].freeze,
    glTexCoord2fColor4fNormal3fVertex3fSUN: [ :void, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glTexCoord2fColor4fNormal3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer, :pointer ].freeze,
    glTexCoord2fColor4ubVertex3fSUN: [ :void, :float, :float, :uchar, :uchar, :uchar, :uchar, :float, :float, :float ].freeze,
    glTexCoord2fColor4ubVertex3fvSUN: [ :void, :pointer, :pointer, :pointer ].freeze,
    glTexCoord2fNormal3fVertex3fSUN: [ :void, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glTexCoord2fNormal3fVertex3fvSUN: [ :void, :pointer, :pointer, :pointer ].freeze,
    glTexCoord2fVertex3fSUN: [ :void, :float, :float, :float, :float, :float ].freeze,
    glTexCoord2fVertex3fvSUN: [ :void, :pointer, :pointer ].freeze,
    glTexCoord4fColor4fNormal3fVertex4fSUN: [ :void, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glTexCoord4fColor4fNormal3fVertex4fvSUN: [ :void, :pointer, :pointer, :pointer, :pointer ].freeze,
    glTexCoord4fVertex4fSUN: [ :void, :float, :float, :float, :float, :float, :float, :float, :float ].freeze,
    glTexCoord4fVertex4fvSUN: [ :void, :pointer, :pointer ].freeze
  }.freeze
end