module GL_VERSION_1_0
  OPTIONS = { ffi: true }.freeze

  FUNCTIONS_COMPATIBILITY = {
    glAccum: [ :void, :uint, :float ].freeze,
    glAlphaFunc: [ :void, :uint, :float ].freeze,
    glBegin: [ :void, :uint ].freeze,
    glBitmap: [ :void, :int, :int, :float, :float, :float, :float, :pointer ].freeze,
    glCallList: [ :void, :uint ].freeze,
    glCallLists: [ :void, :int, :uint, :pointer ].freeze,
    glClearAccum: [ :void, :float, :float, :float, :float ].freeze,
    glClearIndex: [ :void, :float ].freeze,
    glClipPlane: [ :void, :uint, :pointer ].freeze,
    glColor3b: [ :void, :char, :char, :char ].freeze,
    glColor3bv: [ :void, :pointer ].freeze,
    glColor3d: [ :void, :double, :double, :double ].freeze,
    glColor3dv: [ :void, :pointer ].freeze,
    glColor3f: [ :void, :float, :float, :float ].freeze,
    glColor3fv: [ :void, :pointer ].freeze,
    glColor3i: [ :void, :int, :int, :int ].freeze,
    glColor3iv: [ :void, :pointer ].freeze,
    glColor3s: [ :void, :short, :short, :short ].freeze,
    glColor3sv: [ :void, :pointer ].freeze,
    glColor3ub: [ :void, :uchar, :uchar, :uchar ].freeze,
    glColor3ubv: [ :void, :pointer ].freeze,
    glColor3ui: [ :void, :uint, :uint, :uint ].freeze,
    glColor3uiv: [ :void, :pointer ].freeze,
    glColor3us: [ :void, :ushort, :ushort, :ushort ].freeze,
    glColor3usv: [ :void, :pointer ].freeze,
    glColor4b: [ :void, :char, :char, :char, :char ].freeze,
    glColor4bv: [ :void, :pointer ].freeze,
    glColor4d: [ :void, :double, :double, :double, :double ].freeze,
    glColor4dv: [ :void, :pointer ].freeze,
    glColor4f: [ :void, :float, :float, :float, :float ].freeze,
    glColor4fv: [ :void, :pointer ].freeze,
    glColor4i: [ :void, :int, :int, :int, :int ].freeze,
    glColor4iv: [ :void, :pointer ].freeze,
    glColor4s: [ :void, :short, :short, :short, :short ].freeze,
    glColor4sv: [ :void, :pointer ].freeze,
    glColor4ub: [ :void, :uchar, :uchar, :uchar, :uchar ].freeze,
    glColor4ubv: [ :void, :pointer ].freeze,
    glColor4ui: [ :void, :uint, :uint, :uint, :uint ].freeze,
    glColor4uiv: [ :void, :pointer ].freeze,
    glColor4us: [ :void, :ushort, :ushort, :ushort, :ushort ].freeze,
    glColor4usv: [ :void, :pointer ].freeze,
    glColorMaterial: [ :void, :uint, :uint ].freeze,
    glCopyPixels: [ :void, :int, :int, :int, :int, :uint ].freeze,
    glDeleteLists: [ :void, :uint, :int ].freeze,
    glDrawPixels: [ :void, :int, :int, :uint, :uint, :pointer ].freeze,
    glEdgeFlag: [ :void, :uchar ].freeze,
    glEdgeFlagv: [ :void, :pointer ].freeze,
    glEnd: [ :void ].freeze,
    glEndList: [ :void ].freeze,
    glEvalCoord1d: [ :void, :double ].freeze,
    glEvalCoord1dv: [ :void, :pointer ].freeze,
    glEvalCoord1f: [ :void, :float ].freeze,
    glEvalCoord1fv: [ :void, :pointer ].freeze,
    glEvalCoord2d: [ :void, :double, :double ].freeze,
    glEvalCoord2dv: [ :void, :pointer ].freeze,
    glEvalCoord2f: [ :void, :float, :float ].freeze,
    glEvalCoord2fv: [ :void, :pointer ].freeze,
    glEvalMesh1: [ :void, :uint, :int, :int ].freeze,
    glEvalMesh2: [ :void, :uint, :int, :int, :int, :int ].freeze,
    glEvalPoint1: [ :void, :int ].freeze,
    glEvalPoint2: [ :void, :int, :int ].freeze,
    glFeedbackBuffer: [ :void, :int, :uint, :pointer ].freeze,
    glFogf: [ :void, :uint, :float ].freeze,
    glFogfv: [ :void, :uint, :pointer ].freeze,
    glFogi: [ :void, :uint, :int ].freeze,
    glFogiv: [ :void, :uint, :pointer ].freeze,
    glFrustum: [ :void, :double, :double, :double, :double, :double, :double ].freeze,
    glGenLists: [ :uint, :int ].freeze,
    glGetClipPlane: [ :void, :uint, :pointer ].freeze,
    glGetLightfv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetLightiv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetMapdv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetMapfv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetMapiv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetMaterialfv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetMaterialiv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetPixelMapfv: [ :void, :uint, :pointer ].freeze,
    glGetPixelMapuiv: [ :void, :uint, :pointer ].freeze,
    glGetPixelMapusv: [ :void, :uint, :pointer ].freeze,
    glGetPolygonStipple: [ :void, :pointer ].freeze,
    glGetTexEnvfv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetTexEnviv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetTexGenfv: [ :void, :uint, :uint, :pointer ].freeze,
    glGetTexGeniv: [ :void, :uint, :uint, :pointer ].freeze,
    glIndexd: [ :void, :double ].freeze,
    glIndexdv: [ :void, :pointer ].freeze,
    glIndexf: [ :void, :float ].freeze,
    glIndexfv: [ :void, :pointer ].freeze,
    glIndexi: [ :void, :int ].freeze,
    glIndexiv: [ :void, :pointer ].freeze,
    glIndexs: [ :void, :short ].freeze,
    glIndexsv: [ :void, :pointer ].freeze,
    glIndexMask: [ :void, :uint ].freeze,
    glInitNames: [ :void ].freeze,
    glIsList: [ :uchar, :uint ].freeze,
    glLightf: [ :void, :uint, :uint, :float ].freeze,
    glLightfv: [ :void, :uint, :uint, :pointer ].freeze,
    glLighti: [ :void, :uint, :uint, :int ].freeze,
    glLightiv: [ :void, :uint, :uint, :pointer ].freeze,
    glLightModelf: [ :void, :uint, :float ].freeze,
    glLightModelfv: [ :void, :uint, :pointer ].freeze,
    glLightModeli: [ :void, :uint, :int ].freeze,
    glLightModeliv: [ :void, :uint, :pointer ].freeze,
    glLineStipple: [ :void, :int, :ushort ].freeze,
    glListBase: [ :void, :uint ].freeze,
    glLoadIdentity: [ :void ].freeze,
    glLoadMatrixd: [ :void, :pointer ].freeze,
    glLoadMatrixf: [ :void, :pointer ].freeze,
    glLoadName: [ :void, :uint ].freeze,
    glMap1d: [ :void, :uint, :double, :double, :int, :int, :pointer ].freeze,
    glMap1f: [ :void, :uint, :float, :float, :int, :int, :pointer ].freeze,
    glMap2d: [ :void, :uint, :double, :double, :int, :int, :double, :double, :int, :int, :pointer ].freeze,
    glMap2f: [ :void, :uint, :float, :float, :int, :int, :float, :float, :int, :int, :pointer ].freeze,
    glMaterialf: [ :void, :uint, :uint, :float ].freeze,
    glMaterialfv: [ :void, :uint, :uint, :pointer ].freeze,
    glMateriali: [ :void, :uint, :uint, :int ].freeze,
    glMaterialiv: [ :void, :uint, :uint, :pointer ].freeze,
    glMatrixMode: [ :void, :uint ].freeze,
    glMultMatrixd: [ :void, :pointer ].freeze,
    glMultMatrixf: [ :void, :pointer ].freeze,
    glNewList: [ :void, :uint, :uint ].freeze,
    glNormal3b: [ :void, :char, :char, :char ].freeze,
    glNormal3bv: [ :void, :pointer ].freeze,
    glNormal3d: [ :void, :double, :double, :double ].freeze,
    glNormal3dv: [ :void, :pointer ].freeze,
    glNormal3f: [ :void, :float, :float, :float ].freeze,
    glNormal3fv: [ :void, :pointer ].freeze,
    glNormal3i: [ :void, :int, :int, :int ].freeze,
    glNormal3iv: [ :void, :pointer ].freeze,
    glNormal3s: [ :void, :short, :short, :short ].freeze,
    glNormal3sv: [ :void, :pointer ].freeze,
    glOrtho: [ :void, :double, :double, :double, :double, :double, :double ].freeze,
    glPassThrough: [ :void, :float ].freeze,
    glPixelMapfv: [ :void, :uint, :int, :pointer ].freeze,
    glPixelMapuiv: [ :void, :uint, :int, :pointer ].freeze,
    glPixelMapusv: [ :void, :uint, :int, :pointer ].freeze,
    glPixelTransferf: [ :void, :uint, :float ].freeze,
    glPixelTransferi: [ :void, :uint, :int ].freeze,
    glPixelZoom: [ :void, :float, :float ].freeze,
    glPolygonStipple: [ :void, :pointer ].freeze,
    glPopAttrib: [ :void ].freeze,
    glPopMatrix: [ :void ].freeze,
    glPopName: [ :void ].freeze,
    glPushAttrib: [ :void, :uint ].freeze,
    glPushMatrix: [ :void ].freeze,
    glPushName: [ :void, :uint ].freeze,
    glRasterPos2d: [ :void, :double, :double ].freeze,
    glRasterPos2dv: [ :void, :pointer ].freeze,
    glRasterPos2f: [ :void, :float, :float ].freeze,
    glRasterPos2fv: [ :void, :pointer ].freeze,
    glRasterPos2i: [ :void, :int, :int ].freeze,
    glRasterPos2iv: [ :void, :pointer ].freeze,
    glRasterPos2s: [ :void, :short, :short ].freeze,
    glRasterPos2sv: [ :void, :pointer ].freeze,
    glRasterPos3d: [ :void, :double, :double, :double ].freeze,
    glRasterPos3dv: [ :void, :pointer ].freeze,
    glRasterPos3f: [ :void, :float, :float, :float ].freeze,
    glRasterPos3fv: [ :void, :pointer ].freeze,
    glRasterPos3i: [ :void, :int, :int, :int ].freeze,
    glRasterPos3iv: [ :void, :pointer ].freeze,
    glRasterPos3s: [ :void, :short, :short, :short ].freeze,
    glRasterPos3sv: [ :void, :pointer ].freeze,
    glRasterPos4d: [ :void, :double, :double, :double, :double ].freeze,
    glRasterPos4dv: [ :void, :pointer ].freeze,
    glRasterPos4f: [ :void, :float, :float, :float, :float ].freeze,
    glRasterPos4fv: [ :void, :pointer ].freeze,
    glRasterPos4i: [ :void, :int, :int, :int, :int ].freeze,
    glRasterPos4iv: [ :void, :pointer ].freeze,
    glRasterPos4s: [ :void, :short, :short, :short, :short ].freeze,
    glRasterPos4sv: [ :void, :pointer ].freeze,
    glRectd: [ :void, :double, :double, :double, :double ].freeze,
    glRectdv: [ :void, :pointer, :pointer ].freeze,
    glRectf: [ :void, :float, :float, :float, :float ].freeze,
    glRectfv: [ :void, :pointer, :pointer ].freeze,
    glRecti: [ :void, :int, :int, :int, :int ].freeze,
    glRectiv: [ :void, :pointer, :pointer ].freeze,
    glRects: [ :void, :short, :short, :short, :short ].freeze,
    glRectsv: [ :void, :pointer, :pointer ].freeze,
    glRenderMode: [ :int, :uint ].freeze,
    glRotated: [ :void, :double, :double, :double, :double ].freeze,
    glRotatef: [ :void, :float, :float, :float, :float ].freeze,
    glScaled: [ :void, :double, :double, :double ].freeze,
    glScalef: [ :void, :float, :float, :float ].freeze,
    glSelectBuffer: [ :void, :int, :pointer ].freeze,
    glShadeModel: [ :void, :uint ].freeze,
    glTexCoord1d: [ :void, :double ].freeze,
    glTexCoord1dv: [ :void, :pointer ].freeze,
    glTexCoord1f: [ :void, :float ].freeze,
    glTexCoord1fv: [ :void, :pointer ].freeze,
    glTexCoord1i: [ :void, :int ].freeze,
    glTexCoord1iv: [ :void, :pointer ].freeze,
    glTexCoord1s: [ :void, :short ].freeze,
    glTexCoord1sv: [ :void, :pointer ].freeze,
    glTexCoord2d: [ :void, :double, :double ].freeze,
    glTexCoord2dv: [ :void, :pointer ].freeze,
    glTexCoord2f: [ :void, :float, :float ].freeze,
    glTexCoord2fv: [ :void, :pointer ].freeze,
    glTexCoord2i: [ :void, :int, :int ].freeze,
    glTexCoord2iv: [ :void, :pointer ].freeze,
    glTexCoord2s: [ :void, :short, :short ].freeze,
    glTexCoord2sv: [ :void, :pointer ].freeze,
    glTexCoord3d: [ :void, :double, :double, :double ].freeze,
    glTexCoord3dv: [ :void, :pointer ].freeze,
    glTexCoord3f: [ :void, :float, :float, :float ].freeze,
    glTexCoord3fv: [ :void, :pointer ].freeze,
    glTexCoord3i: [ :void, :int, :int, :int ].freeze,
    glTexCoord3iv: [ :void, :pointer ].freeze,
    glTexCoord3s: [ :void, :short, :short, :short ].freeze,
    glTexCoord3sv: [ :void, :pointer ].freeze,
    glTexCoord4d: [ :void, :double, :double, :double, :double ].freeze,
    glTexCoord4dv: [ :void, :pointer ].freeze,
    glTexCoord4f: [ :void, :float, :float, :float, :float ].freeze,
    glTexCoord4fv: [ :void, :pointer ].freeze,
    glTexCoord4i: [ :void, :int, :int, :int, :int ].freeze,
    glTexCoord4iv: [ :void, :pointer ].freeze,
    glTexCoord4s: [ :void, :short, :short, :short, :short ].freeze,
    glTexCoord4sv: [ :void, :pointer ].freeze,
    glTexEnvf: [ :void, :uint, :uint, :float ].freeze,
    glTexEnvfv: [ :void, :uint, :uint, :pointer ].freeze,
    glTexEnvi: [ :void, :uint, :uint, :int ].freeze,
    glTexEnviv: [ :void, :uint, :uint, :pointer ].freeze,
    glTexGend: [ :void, :uint, :uint, :double ].freeze,
    glTexGendv: [ :void, :uint, :uint, :pointer ].freeze,
    glTexGenf: [ :void, :uint, :uint, :float ].freeze,
    glTexGenfv: [ :void, :uint, :uint, :pointer ].freeze,
    glTexGeni: [ :void, :uint, :uint, :int ].freeze,
    glTexGeniv: [ :void, :uint, :uint, :pointer ].freeze,
    glTranslated: [ :void, :double, :double, :double ].freeze,
    glTranslatef: [ :void, :float, :float, :float ].freeze,
    glVertex2d: [ :void, :double, :double ].freeze,
    glVertex2dv: [ :void, :pointer ].freeze,
    glVertex2f: [ :void, :float, :float ].freeze,
    glVertex2fv: [ :void, :pointer ].freeze,
    glVertex2i: [ :void, :int, :int ].freeze,
    glVertex2iv: [ :void, :pointer ].freeze,
    glVertex2s: [ :void, :short, :short ].freeze,
    glVertex2sv: [ :void, :pointer ].freeze,
    glVertex3d: [ :void, :double, :double, :double ].freeze,
    glVertex3dv: [ :void, :pointer ].freeze,
    glVertex3f: [ :void, :float, :float, :float ].freeze,
    glVertex3fv: [ :void, :pointer ].freeze,
    glVertex3i: [ :void, :int, :int, :int ].freeze,
    glVertex3iv: [ :void, :pointer ].freeze,
    glVertex3s: [ :void, :short, :short, :short ].freeze,
    glVertex3sv: [ :void, :pointer ].freeze,
    glVertex4d: [ :void, :double, :double, :double, :double ].freeze,
    glVertex4dv: [ :void, :pointer ].freeze,
    glVertex4f: [ :void, :float, :float, :float, :float ].freeze,
    glVertex4fv: [ :void, :pointer ].freeze,
    glVertex4i: [ :void, :int, :int, :int, :int ].freeze,
    glVertex4iv: [ :void, :pointer ].freeze,
    glVertex4s: [ :void, :short, :short, :short, :short ].freeze,
    glVertex4sv: [ :void, :pointer ].freeze
  }.freeze
end